import { deleteDoc, doc, getDoc, Timestamp } from "firebase/firestore";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Preview } from "../components/Preview";
import { db } from "../utils/firebase";

const App = () => {
	const [data, setData] = useState({
		beforeMessage: "",
		beforePic: "",
		afterMessage: "",
		afterPic: "",
		from: "",
		date: Timestamp.now(),
		url: "",
	});
	const router = useRouter();
	const id = router.query["id"];
	useEffect(() => {
		if (id && typeof id === "string")
			getDoc(doc(db, "message", id)).then((docSnap) => {
				setData(docSnap.data() as any);
				if (docSnap.exists()) {
					deleteDoc(doc(db, "message", id));
				}
			});
	}, [id]);

	return (
		<>
			<Head>
				<title>{data.from}さんからのメッセージ</title>
				{/* <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Preview data={data} />
		</>
	);
};
export default App;
